# desktop is the default view, you could add a mobile view etc.
desktop:
    # define a default template for use in pages
    layout: "layouts/application"
    pages:
        # a root page called index
        index:
            # content contains all the parts of the page, in this case one partial
            content: ["header", "about", "contact", "drinks/cocktails", "drinks/wine", "drinks/beer", "drinks/spirits", "food", "bartenders", "awards"]

#        # Here's an example of nested pages
#        about:
#            the_team:
#                content: ["about/team"]
#            the_company:
#                content: ["about/company"]
